# Generated by Django 4.0.2 on 2022-05-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_menuitem_link_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='link_category',
        ),
    ]
