# Generated by Django 4.0.2 on 2022-04-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='use_other_template',
            field=models.BooleanField(blank=True, help_text='Use a different template', null=True, verbose_name='New Template'),
        ),
    ]
