# Generated by Django 4.0.2 on 2022-04-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_formpage_use_other_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='use_other_template',
            field=models.BooleanField(blank=True, default='No', help_text='Use a different template', null=True, verbose_name='New Template'),
        ),
    ]
