# Generated by Django 4.0.2 on 2022-03-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.RenameField(
            model_name='blogpage',
            old_name='intro',
            new_name='subtitle',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, null=True, verbose_name='slug'),
        ),
    ]
