# Generated by Django 4.0.2 on 2022-03-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='You might add a Subtitle', max_length=250, null=True),
        ),
    ]
