# Generated by Django 4.0.2 on 2022-03-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpagecarousel_carousel_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpagecarousel',
            name='carousel_title',
            field=models.CharField(blank=True, help_text='Add a Title', max_length=250, null=True),
        ),
    ]
