# Generated by Django 4.0.2 on 2022-03-27 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpagecarousel_carousel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Updated'),
        ),
    ]
