# Generated by Django 4.0.2 on 2022-03-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpage_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpagecarousel',
            name='color',
            field=models.CharField(blank=True, choices=[('', 'Select Title Color'), ('W', 'White'), ('B', 'Black'), ('R', 'Red')], default='W', max_length=100),
        ),
    ]
