# Generated by Django 4.0.2 on 2022-03-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogpagecarousel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagecarousel',
            name='color',
            field=models.CharField(blank=True, choices=[('', 'Select Title Color'), ('W', 'White'), ('B', 'Black'), ('R', 'Red')], default='W', help_text='Change Text color', max_length=100),
        ),
    ]
