# Generated by Django 4.0.2 on 2022-04-03 19:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogpagecarousel_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageBlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_pages', to='blog.blogcategory')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories2', to='blog.blogpage')),
            ],
            options={
                'unique_together': {('page', 'blog_category')},
            },
        ),
    ]
