# Generated by Django 4.0.2 on 2022-04-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogcategoryindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
