# Generated by Django 4.0.2 on 2022-04-20 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('blog', '0018_alter_blogpagecarousel_carousel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagecarousel',
            name='carousel_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
