# Generated by Django 4.0.2 on 2022-04-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_bloglistingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingpage',
            name='color',
            field=models.CharField(blank=True, choices=[('', 'Select Title Color'), ('W', 'White'), ('B', 'Black'), ('R', 'Red')], default='W', help_text='Change Text color', max_length=100),
        ),
    ]
