# Generated by Django 4.0.2 on 2022-04-30 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_knowledgebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
