# Generated by Django 4.0.2 on 2022-04-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_knowledgebase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebase',
            name='tags',
        ),
    ]
