# Generated by Django 4.0.2 on 2022-05-02 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('blog', '0027_delete_knowledgebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('body', wagtail.core.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'KnowledgeBase',
                'verbose_name_plural': 'KnowledgeBase',
            },
            bases=('wagtailcore.page',),
        ),
    ]
