# Generated by Django 4.0.2 on 2022-05-02 19:34

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_knowledgebase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagecarousel',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='blog.blogindexpage'),
        ),
    ]
