# Generated by Django 4.0.2 on 2022-05-02 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('blog', '0029_alter_blogpagecarousel_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagecarousel',
            name='carousel_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page'),
        ),
    ]
