# Generated by Django 4.0.2 on 2022-05-22 19:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_remove_bloglistingpage_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglistingpage',
            name='heading',
            field=wagtail.core.fields.StreamField([('jumbotron', wagtail.core.blocks.StructBlock([('jumbotron', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=40, required=False)), ('description', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'bold', 'italic', 'link'], required=False)), ('color', wagtail.core.blocks.CharBlock(help_text='Enter a hexdecimal color for the background e.g #000000', max_length=40, required=False)), ('text_color', wagtail.core.blocks.CharBlock(help_text='Enter a hexdecimal color for the text e.g #000000 or red', max_length=40, required=False))])))]))], blank=True, null=True),
        ),
    ]
