# Generated by Django 4.0.2 on 2022-03-06 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, default='www.instagram.com/', max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, default='www.facebook.com/', max_length=100, null=True)),
                ('twitter', models.URLField(blank=True, default='www.twitter.com/', max_length=100, null=True)),
                ('pinterest', models.URLField(blank=True, default='www.pinterest.com/', max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, default='www.linkedin.com/', max_length=100, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Social Media Channel',
            },
        ),
    ]
