# Generated by Django 4.0.2 on 2022-04-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_socialmediasettings_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='whatsapp',
            field=models.CharField(blank=True, default='Enter your number', help_text='Whatsapp Number', max_length=11, null=True),
        ),
    ]
