# Generated by Django 4.0.2 on 2022-04-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0006_sitesettings_show_in_menu_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_title_in_menu_bar',
            field=models.BooleanField(blank=True, default=False, help_text='Select to show Title in menu bar', verbose_name='Menu Title'),
        ),
    ]
