# Generated by Django 4.0.2 on 2022-05-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='header',
            new_name='heading',
        ),
        migrations.AddField(
            model_name='homepage',
            name='color',
            field=models.CharField(blank=True, help_text='Enter a hexdecimal color for the background e.g #000000', max_length=250, null=True),
        ),
    ]
