# Generated by Django 4.0.2 on 2022-05-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_header_homepage_heading_homepage_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='heading',
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='heading'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='data_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='heading'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='heading'),
        ),
    ]
