# Generated by Django 4.0.2 on 2022-05-24 16:25

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homepage_card_alter_homepage_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='card',
            field=wagtail.core.fields.StreamField([('card', wagtail.core.blocks.StructBlock([('background_color', wagtail.core.blocks.CharBlock(max_length=60, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=60, required=True)), ('text', wagtail.core.blocks.TextBlock(required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Enter', max_length=40, required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact',
            field=wagtail.core.fields.StreamField([('contact', wagtail.core.blocks.StructBlock([('select', wagtail.core.blocks.BooleanBlock(blank=True, help_text='Select to use 2 columns', required=False, verbose_name='Two Columns')), ('background_color', wagtail.core.blocks.CharBlock(max_length=60, required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=60, required=True)), ('text', wagtail.core.blocks.TextBlock(required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Get in Touch', max_length=40, required=False))]))], blank=True, null=True),
        ),
    ]
