# Generated by Django 4.0.2 on 2022-05-27 13:19

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_homepage_card_alter_homepage_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='card',
            field=wagtail.core.fields.StreamField([('card', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=60, required=True)), ('text', wagtail.core.blocks.TextBlock(required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(page_type=['chart.DataListingPage'], required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Enter', max_length=40, required=False))]))], blank=True, null=True),
        ),
    ]
