# Generated by Django 4.0.2 on 2022-05-12 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('chart', '0003_dataindex_datapage'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
