# Generated by Django 4.0.2 on 2022-05-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_datapage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataIndex',
        ),
        migrations.DeleteModel(
            name='DataPage',
        ),
    ]
