# Generated by Django 4.0.2 on 2022-05-15 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0006_dataindex_datapage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
