# Generated by Django 4.0.2 on 2022-09-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0014_datapage_body_alter_datapage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapage',
            name='body',
        ),
    ]
